### ISSUE TITLE
How can we generate ".seg.png" and "id2centers.json"

### ISSUE THREAD

**Issue by Shiming94** [zju3dv/VS-Net#2]
Hey guy,

it is really nice work! Our group is trying to test your method on our datasets. I was wondering if you can provide the script to generate the ".seg.png" files and "id2centers.json" file of each dataset. Meanwhile, do you also have the pre-trained models for the CambridgeLandmarks dataset? 

Best,
Shiming

**Comment by sunxirui310** [comment]
我看了一下处理7scenes数据的脚本，没有找到id2centers.json，是网站下载数据包的内容有变化了吗？无论windows还是Linux都没有找到json文件，或者说告诉我id2centers.json里数据结构和处理流程也行。

多谢多谢！
![image](https://user-images.githubusercontent.com/19179730/155931378-cc8b1893-5e99-48b9-a8ac-87006b714bd5.png)

![image](https://user-images.githubusercontent.com/19179730/155931455-d19bb19b-c8ab-4a0c-b761-fc08f892e69b.png)

**Comment by asdiuzd** [comment]
We provide our preprocessed 7scenes training segmentation images [here](https://drive.google.com/drive/folders/1DzxTL8D7ym5bDWJkZ4FitT-yl2t7jCpr?usp=sharing) and cambridge training segmentation images [here](https://drive.google.com/drive/folders/12N2n5Pof5QuHkTmtewSyKuixZyAFBpwK?usp=sharing). The voting images are generate with the following script.

python scripts/7scenes_preprocess.py --scene scene_name --root_dir /path/to/data
python scripts/cambridge_preprocess.py --scene scene_name --root_dir /path/to/data

**Comment by sunxirui310** [comment]
> We provide our preprocessed 7scenes training segmentation images [here](https://drive.google.com/drive/folders/1DzxTL8D7ym5bDWJkZ4FitT-yl2t7jCpr?usp=sharing) and cambridge training segmentation images [here](https://drive.google.com/drive/folders/12N2n5Pof5QuHkTmtewSyKuixZyAFBpwK?usp=sharing). The voting images are generate with the following script.
> 
> python scripts/7scenes_preprocess.py --scene scene_name --root_dir /path/to/data python scripts/cambridge_preprocess.py --scene scene_name --root_dir /path/to/data

感谢分享。
