### ISSUE TITLE
Pre-trained models for Cambridge

### ISSUE THREAD

**Issue by rpautrat** [zju3dv/VS-Net#4]
Hi,

Thank you very much for this inspiring work and for releasing the implementation code.

I noticed that you give a link to the pre-trained models on 7Scenes, but not on the Cambridge dataset. Would it also be possible to get access to the pre-trained models on Cambridge? Thank you in advance!

**Comment by drinkingcoder** [comment]
The pre-trained models have been updated. Thanks for your attention.

**Comment by rpautrat** [comment]
Thank you very much!!
