### ISSUE TITLE
question about sevenscenes_data

### ISSUE THREAD

**Issue by Jemmagu** [zju3dv/VS-Net#5]
hi, i noticed that the original pose of sevenscenes data is under "camera-to-world" coordinate, so during your training, you converted to "world-to-camera" coordinate by using script " _pose_target = np.linalg.inv(_pose_target)".
but why you added script "_pose_target[0, 3] = _pose_target[0, 3] + 0.0245"?

**Comment by drinkingcoder** [comment]
The 7Scenes dataset compute camera poses via an RGB-D camera, where the RGB camera and the Depth camera has a spatial offset. We use the 0.0245 according to the kinect in our Lab.
